### ISSUE TITLE
Possible mod conflict

### ISSUE THREAD

**Issue by logitechQ** [FruitGooseKSP/MyAntennaeNeverGoOffline#3]
In my modded install (~200 mods) The mod is not working correctly, instead of slowing down transmission on low power, it just seems to make all transmissions instant and basically free. 
I have no idea what this could be but i'd be happy to re-create the bug and to troubleshoot to find the issue.

**Comment by FruitGooseKSP** [comment]
Hi, it does do that with some add-on solar panels (I use Tantares myself and have seen similar). I will look at tweaking it to make it more balanced for those types.

**Comment by FruitGooseKSP** [comment]
Issue fixed. ModuleManager now a dependency (it didn't seem to recognise some of the add-on parts properly so this fixes that). I've also tweaked the transmit time significantly so it _should_  be noticeably slower to transmit. Let me know if still issues.
